{{- if and .Values.tekton.enabled .Values.tekton.triggers.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rhoai-pipelines-demo.labels" . | nindent 4 }}
{{- end }}
