apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: fraud-detection-run-
  namespace: rhoai-playground
spec:
  pipelineRef:
    name: deploy-kfp-pipeline
  params:
    - name: git-url
      value: https://github.com/alvarolop/rhoai-experimentation.git
    - name: git-revision
      value: main
    - name: pipeline-path
      value: pipelines/fraud-detection
    - name: pipeline-name
      value: fraud-detection-pipeline
    - name: pipeline-file
      value: pipeline.py
    - name: wait-for-completion
      value: "true"
    - name: timeout
      value: "3600"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
